# Generated by Django 2.2.3 on 2019-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.CharField(max_length=208, null=True),
        ),
    ]
